### ISSUE TITLE
typedoc-default-themes/bin/default/assets not found

### ISSUE THREAD

**Issue by macrozone** [TypeStrong/typedoc#1428]
## Expected Behavior

freshly installed typedoc, tried in a monorepo:

`yarn typedoc packages/editor/src/index.tsx --out api-docs --tsconfig packages/editor/tsconfig.json`

should just work

## Actual Behavior

it throws an error

```
TypeDoc exiting with unexpected error:
Error: ENOENT: no such file or directory, stat '/path/to/project/node_modules/typedoc-default-themes/bin/default/assets'
    at Object.statSync (fs.js:915:3)
    at Object.statSync (/path/to/project/node_modules/graceful-fs/polyfills.js:307:34)
    at statSync (/path/to/project/node_modules/typedoc/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/path/to/project/node_modules/typedoc/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/path/to/project/node_modules/typedoc/node_modules/fs-extra/lib/util/stat.js:49:33)
    at Object.copySync (/path/to/project/node_modules/typedoc/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at AssetsPlugin.onRendererBegin (/path/to/project/node_modules/typedoc/dist/lib/output/plugins/AssetsPlugin.js:43:16)
    at /path/to/project/node_modules/typedoc/dist/lib/utils/events.js:366:33
    at triggerApi (/path/to/project/node_modules/typedoc/dist/lib/utils/events.js:149:13)
    at Renderer.trigger (/path/to/project/node_modules/typedoc/dist/lib/utils/events.js:358:13) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/path/to/project/node_modules/typedoc-default-themes/bin/default/assets'
}
✨  Done in 7.64s.
```

## Steps to reproduce the bug

i guess its a bug in the newest version that was released yesterday. 

The folder `assets` is indeed not present:

```
$ ls node_modules/typedoc-default-themes/bin/default      
# shows these folders:

layouts   partials  templates
```
## Environment

-   Typedoc version: 0.20.1
-  typedoc-default-themes: 0.12.0
-   TypeScript version: 4.0.5
-   Node.js version: v12.13.1
-   OS: macOS big sur

**Comment by macrozone** [comment]
might be a lerna problem

**Comment by Gerrit0** [comment]
Yeah, I don't think this is a typedoc problem - I don't see this issue in a standard repo using either plain npm or yarn. (Well, besides the inherit problem of using a second package as "file storage"...)

**Comment by macrozone** [comment]
@Gerrit0 i guess lerna's symlinking might mess with it. Is there some magic with this asset folder?

**Comment by Gerrit0** [comment]
It isn't any more magical than the layouts/partials/templates folders, so I don't know what could be going on... Besides a reinstall, I'm not sure what to tell you

**Comment by Gerrit0** [comment]
Closing as unactionable without a reproduction, please reopen if you are able to provide one.

**Comment by RichardIvan** [comment]
Actually, the assets folder is cleaned up by yarn.

More info in [this issue](https://github.com/yarnpkg/yarn/issues/2803).
