### ISSUE TITLE
Assertion failed checking if declaration is parameter

### ISSUE THREAD

**Issue by benmccann** [TypeStrong/typedoc#1443]
## Search terms

>TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

## Expected Behavior

Expected docs to generate without error

## Actual Behavior

```
$ npx typedoc 
TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(declaration &&
      (ts.isParameter(declaration) ||
          ts.isJSDocParameterTag(declaration)))

    at /node_modules/typedoc/dist/lib/converter/factories/signature.js:40:9
    at Array.map (<anonymous>)
    at convertParameters (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/factories/signature.js:38:23)
    at Object.createSignature (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/factories/signature.js:24:25)
    at Object.convertFunctionOrMethod (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/symbols.js:162:39)
    at convertSymbol (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/symbols.js:76:79)
    at convertSymbols (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/symbols.js:82:9)
    at Object.convertClassOrInterface (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/symbols.js:205:5)
    at convertSymbol (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/symbols.js:76:79)
    at Object.convertAlias (/home/bmccann/src/Chart.js/node_modules/typedoc/dist/lib/converter/symbols.js:365:9) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

## Steps to reproduce the bug

```
git clone https://github.com/benmccann/Chart.js
cd Chart.js
git checkout typedoc-upgrade
npm install
npx typedoc
```

## Environment

-   Typedoc version: 0.20.7
-   TypeScript version: 4.1.3
-   Node.js version: 14.8.0
-   OS: Ubuntu

**Comment by Gerrit0** [comment]
Well, that's annoying... `arguments` is the issue here. TS knows there is a rest parameter, but there is no declaration for it.

```js
	/**
	 * @private
	 */
	_onDataPush() {
		const count = arguments.length;
		this._insertElements(this.getDataset().data.length - count, count);
	}
```

**Comment by Gerrit0** [comment]
Fixed in 0.20.9, plus another bug that this revealed

**Comment by benmccann** [comment]
Wow, amazing! Thanks for the super fast look at this!! :smiley:

**Comment by benmccann** [comment]
It looks like publishing 0.20.9 might have failed. It's not available and I see a red X here: https://github.com/TypeStrong/typedoc/runs/1635049281

**Comment by Gerrit0** [comment]
Shoot, sorry about that. I was rushing to push the change and go to a friend's, so didn't properly test things. Published now!

**Comment by benmccann** [comment]
awesome. thanks!  It looks like 0.20 is working on Chart.js now, so I just sent a PR to upgrade it :smiley:
