### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Should be impossible, disallowed by converter after upgrading to 0.20.31

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1538]
## Search terms

AssertionError [ERR_ASSERTION]: Should be impossible, disallowed by converter.

## Actual Behavior

After upgrading from 0.20.30 to 0.20.31 the following assertion is thrown:

```
TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: Should be impossible, disallowed by converter.
    at ImplementsPlugin.getExtensionInfo (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/plugins/ImplementsPlugin.js:147:18)
    at ImplementsPlugin.onDeclaration (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/plugins/ImplementsPlugin.js:170:27)
    at triggerEvents (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/utils/events.js:183:43)
    at triggerApi (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/utils/events.js:149:13)
    at eventsApi (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/utils/events.js:42:18)
    at Converter.trigger (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/utils/events.js:371:13)
    at Context.trigger (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/context.js:163:24)
    at Object.convertType (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/types.js:165:17)
    at convertType (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/types.js:100:34)
    at /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/types.js:643:64 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

## Environment

-   Typedoc version: 0.20.31
-   TypeScript version: 4.2.3
-   Node.js version: 14.16.0
-   OS: macOS 11.2.3

**Comment by Gerrit0** [comment]
This is completely unactionable without a reproduction.

**Comment by doberkofler** [comment]
@Gerrit0 I understand, but could you help me to trace the problem down? The assert does not give an indication on what source file caused the error and without that information, I would not know where to start.

**Comment by Gerrit0** [comment]
If you open `node_modules/typedoc/dist/lib/converter/plugins/ImplementsPlugin.js` and modify the assert to include `reflection.getFullName()`, that should help narrow it down

**Comment by doberkofler** [comment]
The problem can be reproduced with the following example:

```typescript
export class UiElement {}

export class UiForm {
	/**
	 * Get the element by name.
	 */
	public getElementByName<T=UiElement>(elementName: string, cls?: new (...a: Array<any>) => T): T {
		return null as unknown as T;
	}
}
```

**Comment by doberkofler** [comment]
> ... I should probably create a custom assert function that automatically annotates assert messages with useful info. It's entirely too easy to forget to do it somewhere.

This would be a great improvement. After your reply, I remembered to already have modified the assert in the past but just forgot.

**Comment by Gerrit0** [comment]
Doh. Of course that fails.. I'm just surprised none of the existing tests ran into that... thanks for the repro!
