### ISSUE TITLE
Package subpath is not defined by "exports"

### ISSUE THREAD

**Issue by Drarig29** [TypeStrong/typedoc#1689]
## Search terms

plugin could not be loaded, exports, esm, package subpath not defined

## Expected Behavior

TypeDoc doesn't work in my TypeDoc plugin repo when I use the `npm link` command.
I don't know if this command is the culprit though.

## Actual Behavior

```
Error: The plugin typedoc-plugin-extras could not be loaded.
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/output/components' is not defined by "exports" in /home/corentin/playground/typedoc-plugin-extras/node_modules/typedoc/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/corentin/playground/typedoc-plugin-extras/dist/plugin.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

## Steps to reproduce the bug

- `git clone https://github.com/Drarig29/typedoc-plugin-extras`
- `git checkout esm`
- `npm install`
- `npm link && npm link typedoc-plugin-extras`
- `npm run build`
- `npm run test`

This only occurs when I load my plugin. If I do `npx typedoc --plugin none src/index.ts`, it works (no plugins loaded).

## Environment

-   Typedoc version: 0.22.3
-   TypeScript version: 4.4.3
-   Node.js version: v14.15.5
-   OS: Manjaro Linux

**Comment by Gerrit0** [comment]
This is a problem with typedoc-plugin-extras. It tries to do:

```ts
import { RendererEvent } from 'typedoc/dist/lib/output/events';
```

Which is blocked in 0.22. You should instead import `RendererEvent` from `typedoc` directly rather than reaching into an internal path.

**Comment by Drarig29** [comment]
Oh thank you! I kept this import because I hadn't reloaded my vscode, and `RendererEvent` was not exported.
