### ISSUE TITLE
Error: 105,110,118,97,108,105,100,...

### ISSUE THREAD

**Issue by GauBen** [TypeStrong/typedoc#1801]
## Search terms

onigasm, marked, Error: 105,110,118,97,108,105,100,..., invalid pattern in look-behind

## Expected Behavior

Produce a short documentation

## Actual Behavior

```console
Warning: You are running with an unsupported TypeScript version! TypeDoc supports 4.0, 4.1, 4.2, 4.3, 4.4
TypeDoc exiting with unexpected error:
Error: 105,110,118,97,108,105,100,32,112,97,116,116,101,114,110,32,105,110,32,108,111,111,107,45,98,101,104,105,110,100
Please report this to https://github.com/markedjs/marked.
    at OnigScanner.findNextMatchSync (/home/Gautier/projects/svelte-tenor/node_modules/onigasm/lib/OnigScanner.js:100:27)
    at /home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:9891
    at R (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:10242)
    at f (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:12144)
    at S (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:11997)
    at w (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:9336)
    at f (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:13085)
    at S (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:11997)
    at e._tokenize (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:8354)
    at e.tokenizeLine2 (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:7575)
```

I tried downgrading to typescript 4.4 and it only removes the warning.

## Steps to reproduce the bug

1. `git clone https://github.com/GauBen/svelte-tenor && cd svelte-tenor`
2. `yarn install`
3. `yarn add typedoc`
4. `yarn typedoc src/lib`

## Environment

-   TypeDoc version: 0.22.9
-   TypeScript version: 4.5.2 / 4.4.4
-   Node.js version: 16.13.0
-   OS: Ubuntu 2004

## See also
TypeDoc blames Marked, but it does not seem to be caused by Marked https://github.com/markedjs/marked/issues/2295

## Edit

Just noticed that
```console
$ String.fromCharCode(105,110,118,97,108,105,100,32,112,97,116,116,101,114,110,32,105,110,32,108,111,111,107,45,98,101,104,105,110,100)
'invalid pattern in look-behind'
```

**Comment by Gerrit0** [comment]
This is a problem with Shiki, likely with the svelte grammar.. I'll try to take a closer look this week (probably Tuesday)

**Comment by Gerrit0** [comment]
I've sent a PR to Shiki which will fix this issue, need it to be merged to fix it here.

**Comment by Gerrit0** [comment]
This should be fixed now - were using a newer version of Shiki which includes the necessary patch. Please reopen if you're still seeing the issue with the latest version.
