### ISSUE TITLE
Bug: TypeDoc build fails when assigning a private instance field to a block scoped const.

### ISSUE THREAD

**Issue by aaclayton** [TypeStrong/typedoc#1931]
## Search terms
Unexpected PrivateIdentifier

## Setup
Using TypeDoc to build documentation for a project which includes some pure JS files

Target file: **example.js**
```js
class SomeClass {
  #privateArray;
  doThing() {
    const items = this.#privateArray || [];
    return items;
  }
}
```
TypeDoc config:
```json
{
  "$schema": "https://typedoc.org/schema.json",
  "name": "Example Bug"
  "entryPoints": ["example.js"],
  "out": "_docs",
}
```

## Expected Behavior
I expect `npm run docs` to build the documentation.

## Actual Behavior
See the following error (replaced my actual path with `<PROJECT_PATH>`:
```
TypeDoc exiting with unexpected error:
Error: Debug Failure. Unexpected PrivateIdentifier in name expression with literal-like access.
    at isSameEntityName (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:16324:26)
    at getEffectiveInitializer (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:16203:63)
    at Object.getDeclaredExpandoInitializer (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:16211:20)
    at getTypeForVariableLikeDeclaration (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:54843:118)
    at getWidenedTypeForVariableLikeDeclaration (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:55309:56)
    at getTypeOfVariableOrParameterOrPropertyWorker (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:55462:24)
    at getTypeOfVariableOrParameterOrProperty (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:55355:28)
    at getTypeOfSymbol (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:55764:24)
    at checkVariableLikeDeclaration (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:80966:41)
    at checkVariableDeclaration (<PROJECT_PATH>\node_modules\typescript\lib\typescript.js:81042:13)
```

## Steps to reproduce the bug
Create a project using my example JS file above.

## Environment

-   Typedoc version: typedoc@0.22.15
-   TypeScript version: typescript@4.6.4
-   Node.js version: v16.14.0
-   OS: Windows 11

**Comment by Gerrit0** [comment]
This appears to be a TypeScript bug. I can reproduce by trying to compile the example file just with tsc. Not something I can fix here...

**Comment by aaclayton** [comment]
Sorry I didn't test whether it was an upstream issue or not before opening this. I can perhaps open the same issue in the typescript repo.

**Comment by Gerrit0** [comment]
Yep, that's probably the best thing to do. They're generally pretty quick with resolving crashes like that.
