### ISSUE TITLE
Exception "TypeError: Cannot read properties of undefined (reading 'text')     at postProcessComment "

### ISSUE THREAD

**Issue by doberkofler** [TypeStrong/typedoc#1967]
## Search terms

TypeError: Cannot read properties of undefined (reading 'text') 

## Expected Behavior

No exception

## Actual Behavior

TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'text')
    at postProcessComment (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/comments/parser.js:82:44)
    at parseComment (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/comments/parser.js:33:5)
    at getCommentWithCache (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/comments/index.js:26:49)
    at getCommentImpl (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/comments/index.js:39:21)
    at getComment (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/comments/index.js:58:12)
    at Context.postReflectionCreation (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/context.js:122:60)
    at Context.createDeclarationReflection (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/context.js:112:14)
    at Object.convertFunctionOrMethod (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/symbols.js:230:32)
    at convertSymbol (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/symbols.js:132:41)
    at convertSymbols (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/typedoc/dist/lib/converter/symbols.js:138:9)

## Steps to reproduce the bug

The exception does not show where the error originates from

## Environment

-   Typedoc version: 0.23.2
-   TypeScript version: 4.7.4
-   Node.js version: 18.4.0
-   OS: maCOS 12.2

**Comment by Gerrit0** [comment]
Oh that's fun, looks like it can be caused by this:

```ts
/**
 * @example
 */
```

**Comment by Gerrit0** [comment]
Thought I'd be able to get this out today, but want to get #1966 in it too, so will be tomorrow

**Comment by doberkofler** [comment]
Thank you for caring and all the great work you are doing
