### ISSUE TITLE
TypeError: theme.owner.attemptExternalResolution is not a function

### ISSUE THREAD

**Issue by Jason3S** [TypeStrong/typedoc#2051]
Looks like removing `attemptExternalResolution` in 0.23.14 broke `typedoc-plugin-markdown`

<img width="951" alt="image" src="https://user-images.githubusercontent.com/3740137/188328625-2759ef8a-fa78-46c5-a989-4a740b883e42.png">

There is a related issue on `typedoc-plugin-markdown`: https://github.com/tgreyuk/typedoc-plugin-markdown/issues/344

<details>
<summary>Stack Dump</summary>

```text
TypeDoc exiting with unexpected error:
TypeError: theme.owner.attemptExternalResolution is not a function
    at Object.attemptExternalResolution (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/attemptExternalResolution.js:6:28)
    at getReferenceType (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:119:44)
    at ReferenceType.<anonymous> (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:10:20)
    at getType (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/declaration-title.js:16:41)
    at DeclarationReflection.<anonymous> (/home/runner/work/cspell/cspell/node_modules/.pnpm/typedoc-plugin-markdown@3.13.5_typedoc@0.23.14/node_modules/typedoc-plugin-markdown/dist/resources/helpers/declaration-title.js:27:17)
    at DeclarationReflection.wrapper (/home/runner/work/cspell/cspell/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at Object.eval [as main] (eval at createFunctionContext (/home/runner/work/cspell/cspell/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:10:248)
    at main (/home/runner/work/cspell/cspell/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at Object.ret (/home/runner/work/cspell/cspell/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at Object.ret [as member.declaration] (/home/runner/work/cspell/cspell/node_modules/.pnpm/handlebars@4.7.7/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
```

</details>

## Search terms

TypeError: theme.owner.attemptExternalResolution is not a function

**Comment by Gerrit0** [comment]
typedoc-plugin-markdown used a function marked `@internal`, which is **not** part of the public API, and therefore breaking changes may be made to it under a patch release.

**Comment by Jason3S** [comment]
> typedoc-plugin-markdown used a function marked `@internal`, which is **not** part of the public API, and therefore breaking changes may be made to it under a patch release.

I understand that. I just raised the issue here for awareness.
