### ISSUE TITLE
Unable to run typedoc

### ISSUE THREAD

**Issue by supriyavedpathak** [TypeStrong/typedoc#2116]
## Search terms

Hi team,
I m unbale to run typedoc with the latest version.

    "typedoc": "^0.23.21",

    "typescript": "^4.7.2"

I m getting below error

$ npx typedoc --version

C:\work \node_modules\typedoc\dist\lib\application.js:163

            ts.sys.clearScreen?.();

                               ^

 

SyntaxError: Unexpected token '.'

    at Module._compile (internal/modules/cjs/loader.js:891:18)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)

    at Module.load (internal/modules/cjs/loader.js:811:32)

    at Function.Module._load (internal/modules/cjs/loader.js:723:14)

    at Module.require (internal/modules/cjs/loader.js:848:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (C:\work \node_modules\typedoc\dist\index.js:18:21)

    at Module._compile (internal/modules/cjs/loader.js:955:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)

**Comment by Gerrit0** [comment]
You're running with a really old node version, will need to update to a supported one.

**Comment by Gerrit0** [comment]
https://github.com/TypeStrong/typedoc/blob/master/CHANGELOG.md#v0230-2022-06-26

**Comment by supriyavedpathak** [comment]
Its not even working for v0.22.18

**Comment by supriyavedpathak** [comment]
Its working now.May I know the theme you are using for example provided by you. Where the icons for class is square with c?

**Comment by Gerrit0** [comment]
That is the default theme of 0.23, it's not available for older versions
