### ISSUE TITLE
Resource not found "reflection.hbs"

### ISSUE THREAD

**Issue by shaddockh** [TypeStrong/typedoc#227]
In the latest version (```0.4.1```), I'm getting an error trying to locate ```reflection.hbs```.  I'm using a custom theme, but only overriding a couple .hbs files.  My understanding is that any files not detected in the custom theme folder would be loaded in from the default theme.

Backing down to ```0.3.12``` resolves the error.

**Comment by kamranayub** [comment]
Yeah, can repro this and I cloned the current master of typedoc-default-themes. Happens when I try to pass in through `--theme`.

**Comment by lisss** [comment]
Any updates on this? It's still an issue when trying to use `minimal` theme - the reflection.hbs is missing from templates directory for this theme (although present for default)

**Comment by blakeembrey** [comment]
Could someone in this thread please test https://github.com/TypeStrong/typedoc/pull/252? I've not used TypeDoc with a custom theme, nor can I see anywhere that this functionality has possibly been removed. 

The issue @kamranayub alludes to should be unrelated, since yes, the files are no longer checked in but no, they still exist if you do an NPM install. This is because checked in built assets are really hard to maintain, just looking through the commit log to find out how this feature could have disappeared is near impossible.

**Comment by shaddockh** [comment]
I just pulled down your branch and tried it out and it appears to still be a problem.
```

Using TypeScript 1.8.10 from /Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typescript/lib
/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/output/utils/resources/stack.js:98
        throw new Error(Util.format("Cannot find resource `%s`.", name));
        ^

Error: Cannot find resource `reflection.hbs`.
    at TemplateStack.ResourceStack.getResource (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/output/utils/resources/stack.j
s:98:15)

    at Renderer.renderDocument (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/output/renderer.js:57:73)
    at /Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/output/renderer.js:46:23
    at Array.forEach (native)
    at Renderer.render (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/output/renderer.js:45:25)
    at CliApplication.Application.generateDocs (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/application.js:91:23)
    at CliApplication.bootstrap (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/cli.js:56:26)
    at CliApplication.Application (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/application.js:33:14)
    at new CliApplication (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/lib/cli.js:29:16)
    at Object.<anonymous> (/Users/shaddockh/Development/Atomic/AtomicMaster/AtomicGameEngine/Artifacts/Build/JSDoc/node_modules/typedoc/bin/typedoc:4:1)
```

**Comment by shaddockh** [comment]
Oops, nevermind..had wrong branch.  This did work with the ```fallback-to-default-theme``` branch.

**Comment by felixfbecker** [comment]
Having the same issue when using the `minimal` theme

**Comment by sergiusignacius** [comment]
Hey guys,

Minimal theme isn't working on the current release; it shows the same error as @shaddockh showed. Running from source does produce the expected result though.

Any news on this?

Cheers,

**Comment by blakeembrey** [comment]
https://github.com/TypeStrong/typedoc/releases/tag/v0.4.5
