### ISSUE TITLE
Typedoc 0.24.x gives TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by jugglingcats** [TypeStrong/typedoc#2298]
## Search terms

ERR_INVALID_ARG_TYPE
NodeError
ReflectionSymbolId

## Expected Behavior

Be able to create simple project using typedoc API without error.

## Actual Behavior

Using version 0.23.28 project runs fine, but gives the following exception with 0.24.x:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at relative (node:path:497:5)
    at ReflectionSymbolId.toObject (C:\Users\alfie\tmp\typedoc-test\node_modules\.pnpm\typedoc@0.24.7_typescript@5.0.4\node_modules\typedoc\dist\lib\models\reflections\ReflectionSymbolId.js:49:66)     
    at C:\Users\alfie\tmp\typedoc-test\node_modules\.pnpm\typedoc@0.24.7_typescript@5.0.4\node_modules\typedoc\dist\lib\models\reflections\project.js:214:35
    at Map.forEach (<anonymous>)
    at ProjectReflection.toObject (C:\Users\alfie\tmp\typedoc-test\node_modules\.pnpm\typedoc@0.24.7_typescript@5.0.4\node_modules\typedoc\dist\lib\models\reflections\project.js:213:40)
    at Serializer.toObject (C:\Users\alfie\tmp\typedoc-test\node_modules\.pnpm\typedoc@0.24.7_typescript@5.0.4\node_modules\typedoc\dist\lib\serialization\serializer.js:21:69)
    at file:///C:/Users/alfie/tmp/typedoc-test/typedoc-verify.mjs:25:24
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

## Steps to reproduce the bug

See https://github.com/jugglingcats/typedoc-test for basic reproduction. Here is the node script that uses the typedoc API:
```
import {Application, TSConfigReader, TypeDocReader} from "typedoc"

const app = new Application()
app.options.addReader(new TypeDocReader())
app.options.addReader(new TSConfigReader())

app.bootstrap({
    entryPoints: ["./test.ts"],
    tsconfig: "./tsconfig.json",
    skipErrorChecking: true
})

try {
    const project = app.convert()

    if (project) {
        app.serializer.toObject(project)
    } else {
        console.log("No typedoc generated!")
    }
} catch (error) {
    throw error
}
```

And the input Typescript file:
```
/**
 * This is a foo.
 */
export const FOO = "bar"
```

And the tsconfig.json:
```
{
    "compilerOptions": {
        "noEmit": true,
    },
    "files": [
        "./test.ts"
    ]
}
```

## Environment

-   Typedoc version: 0.24.0
-   TypeScript version: 5.0.4
-   Node.js version: v16.14.2
-   OS: Windows 11

**Comment by jugglingcats** [comment]
Should have added that I checked the breaking changes for 0.24.0 but couldn't see anything immediately relevant. Thanks.

**Comment by Gerrit0** [comment]
> skipErrorChecking: true

Does it crash with this turned off? Crashes with it on are out of scope.

**Comment by Gerrit0** [comment]
Also... pay attention to types! They're important. app.convert() is async as of like 0.22 iirc

**Comment by jugglingcats** [comment]
> > skipErrorChecking: true
> 
> Does it crash with this turned off? Crashes with it on are out of scope.

Yes it's on, thanks

**Comment by jugglingcats** [comment]
> Also... pay attention to types! They're important. app.convert() is async as of like 0.22 iirc

@Gerrit0 sorry I don't understand the first bit of your message. And `app.convert()` does not appear to be async... 

```
    const project = app.convert()
    console.log("project=", project)
```
gives:
```
$ node typedoc-verify.mjs 
project= <ref *1> ProjectReflection {
  flags: ReflectionFlags(0) [ flags: 0 ],
  id: 0,
  parent: undefined,
  name: 'typedoc-test',
  kind: 1,
  variant: 'project',
  symbolToReflectionIdMap: StableKeyMap {
  ...
```
The problem appears to be in `app.serializer.toObject` call.

**Comment by Gerrit0** [comment]
Oops, sorry, looks like I was mixing up a beta branch... I didn't notice that you were using toObject. toObject is intended for serializing children of projects, you want projectToObject instead.

```js
// @ts-check
import { Application, TSConfigReader, TypeDocReader } from "typedoc";

const app = new Application();
app.options.addReader(new TypeDocReader());
app.options.addReader(new TSConfigReader());

app.bootstrap({
  entryPoints: ["./test.ts"],
  tsconfig: "./tsconfig.json",
  skipErrorChecking: true,
});

try {
  const project = app.convert();

  if (project) {
    app.serializer.projectToObject(project, process.cwd());
  } else {
    console.log("No typedoc generated!");
  }
} catch (error) {
  throw error;
}
```

**Comment by jugglingcats** [comment]
Thanks @Gerrit0, it's working.
