### ISSUE TITLE
Uncaught ReferenceError: __dirname is not defined in browser using ReflectionKind

### ISSUE THREAD

**Issue by jugglingcats** [TypeStrong/typedoc#2305]
## Search terms

ReflectionKind
__dirname
browser

## Expected Behavior

Should be fully usable in the browser (I assume!).

## Actual Behavior

Whenever there is any reference to ReflectionKind, the below error is given:
```
Uncaught ReferenceError: __dirname is not defined
    at node_modules/.pnpm/typedoc@0.24.8_typescript@5.0.4/node_modules/typedoc/dist/lib/utils/general.js (general.js:47:80)
    at __require2 (chunk-X5MHFPH7.js?v=2a9ce4ae:19:50)
    at node_modules/.pnpm/typedoc@0.24.8_typescript@5.0.4/node_modules/typedoc/dist/lib/utils/index.js (index.js:57:17)
    at __require2 (chunk-X5MHFPH7.js?v=2a9ce4ae:19:50)
    at node_modules/.pnpm/typedoc@0.24.8_typescript@5.0.4/node_modules/typedoc/dist/lib/models/comments/comment.js (comment.js:4:17)
    at __require2 (chunk-X5MHFPH7.js?v=2a9ce4ae:19:50)
    at node_modules/.pnpm/typedoc@0.24.8_typescript@5.0.4/node_modules/typedoc/dist/lib/models/reflections/abstract.js (abstract.js:5:19)
    at __require2 (chunk-X5MHFPH7.js?v=2a9ce4ae:19:50)
    at node_modules/.pnpm/typedoc@0.24.8_typescript@5.0.4/node_modules/typedoc/dist/lib/models/reflections/index.js (index.js:4:18)
    at __require2 (chunk-X5MHFPH7.js?v=2a9ce4ae:19:50)
```

This makes it hard for us to update to 0.24.x. I don't know if this is specific to the vite/esbuild bundler.

## Steps to reproduce the bug

https://github.com/jugglingcats/typedoc-test

Run `pnpm install` (or npm/yarn)
Run `node_modules/.bin/vite`

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.0.4
-   Node.js version: v18.16.0
-   OS: Windows 11

**Comment by jugglingcats** [comment]
Interesting, I went back to 0.23.28 and the problem still occurs. Previously we were not using ReflectionKind, but were using `kindString`. So per the release notes breaking changes I was attempting to switch to `ReflectionKind.singularString` and so hit this error for the first time.

**Comment by Gerrit0** [comment]
Yeah... typedoc doesn't support any environment but Node. I'd like to support the browser someday, but that's *very* far down the priority list

**Comment by jugglingcats** [comment]
Thanks, good to know. I managed to work around this issue by defining a "local" ReflectionKindLocal and just copying the enum numeric values over - not great but will do for now. It's interesting that the types _including the enum numeric values_ are in the `.d.ts` file(s) and therefore shouldn't add to the bundle, but even just de-referencing `ReflectionKind.Class` or other enum values causes an issue in this case. I wonder if that's because you've extended the enum with behaviour 🤷 .

Anyway, thanks for fast response as ever.
