### ISSUE TITLE
TypeError: _.unique is not a function

### ISSUE THREAD

**Issue by norenma** [TypeStrong/typedoc#235]
Hi,

I installed typedoc today using: 

`npm install -global typedoc`

When I try to run "typedoc" or any command using typedock I get this error: 

```
/Users/Markus/.npm-packages/lib/node_modules/typedoc/lib/utils/options/options.js:118
        return _.unique(result);
                 ^

TypeError: _.unique is not a function
    at Options.getDeclarationsByScope (/Users/Markus/.npm-packages/lib/node_modules/typedoc/lib/utils/options/options.js:118:18)
    at getParameterHelp (/Users/Markus/.npm-packages/lib/node_modules/typedoc/lib/utils/options/help.js:5:30)
    at Object.getOptionsHelp (/Users/Markus/.npm-packages/lib/node_modules/typedoc/lib/utils/options/help.js:34:19)
    at CliApplication.bootstrap (/Users/Markus/.npm-packages/lib/node_modules/typedoc/lib/cli.js:44:41)
    at CliApplication.Application (/Users/Markus/.npm-packages/lib/node_modules/typedoc/lib/application.js:33:14)
    at new CliApplication (/Users/Markus/.npm-packages/lib/node_modules/typedoc/lib/cli.js:29:16)
    at Object.<anonymous> (/Users/Markus/.npm-packages/lib/node_modules/typedoc/bin/typedoc:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

"typedoc -v" works however: 

```
typedoc -v

TypeDoc 0.4.3
Using TypeScript 1.8.10 from /Users/Markus/.npm-packages/lib/node_modules/typedoc/node_modules/typescript/lib
```
Anyone know how to solve this? 

Thanks in advance, 
Markus

**Comment by NikitaEgorov** [comment]
Hi @norenma 
I the same issue. How you solve it?

**Comment by phongkien** [comment]
This is still occurring in typedoc version 0.4.3. This is due to having lodash version 4.x.x which removed _.unique function and replace it with _.uniq.
