### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by NikitaEgorov** [TypeStrong/typedoc#236]
I have issue with my project

```
Absolute:interfaces/iasyncfunc2.html
Local:classes/elementfactory.html
Absolute:globals.html#observableorpla
Local:classes/elementfactory.html
Absolute:interfaces/iasyncfunc2.html
Local:classes/elementfactory.html
Absolute:undefined
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at MarkedPlugin.ContextAwareRendererComponent.getRelativeUrl
```

it's imports

```ts
// 3d partry modules
import * as $ko from 'knockout';

// Infrastructure modules
import 'system/widgets/bindings/all';
import {IDataSource} from 'system/dataSource';
import {IViewModel} from 'system/view-models';
import {Definition} from 'system/schemaDefinitionBuilder';
import {ObservableOrPlain} from 'system/internal/types';
import {IAsyncFunc2} from 'system/async';


// Internal modules
import * as $i from 'system/binding-definition/bindings/interfaces';
import * as $b from 'system/binding-definition/bindings';

enum ModeType {
    Legacy,
    Edge
}
```

**Comment by janb87** [comment]
Had the same issue. I have a Fix. Will create a pull request tomorrow.

It is caused by a breaking change in nodejs 6.
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#path
