### ISSUE TITLE
TypeError: Cannot assign to read only property 'options' of object '#<Object>'

### ISSUE THREAD

**Issue by phun-ky** [TypeStrong/typedoc#2367]
## Search terms

TypeError Options

## Expected Behavior

No error given

## Actual Behavior

Get this error:

```
[info] Loaded plugin typedoc-plugin-markdown
/home/alexander/Workspace/knowit/internal/devplatform-devkit-js/node_modules/typedoc/dist/lib/utils/options/options.js:103
                this._values[declaration.name] = (0, declaration_2.getDefaultValue)(declaration);
                                               ^
TypeError: Cannot assign to read only property 'options' of object '#<Object>'
    at Options.reset (/home/alexander/Workspace/knowit/internal/devplatform-devkit-js/node_modules/typedoc/dist/lib/utils/options/options.js:103:48)
    at Application.bootstrap (/home/alexander/Workspace/knowit/internal/devplatform-devkit-js/node_modules/typedoc/dist/lib/application.js:118:22)
    at Application.bootstrapWithPlugins (/home/alexander/Workspace/knowit/internal/devplatform-devkit-js/node_modules/typedoc/dist/lib/application.js:103:14)
```

## Steps to reproduce the bug

I get the error with this code:

```js
import { globSync } from 'glob';
import TypeDoc from 'typedoc';

const createDocs = async () => {
  const app = new TypeDoc.Application();

  // If you want TypeDoc to load tsconfig.json / typedoc.json files
  app.options.addReader(new TypeDoc.TSConfigReader());
  app.options.addReader(new TypeDoc.TypeDocReader());

  const entryPoints = globSync(['./packages/*/*/src/index.ts'], {
    ignore: ['**/node_modules/**']
  });

  app.bootstrapWithPlugins({
    // typedoc options here
    entryPoints,
    gitRevision: 'main',
    githubPages: false,
    tsconfig: './tsconfig.json',
    readme: 'none',
    plugin: ['typedoc-plugin-markdown']
  });

  const project = app.convert();

  if (project) {
    // Project may not have converted correctly
    const outputDir = '@docs';

    // Rendered docs
    await app.generateDocs(project, outputDir);
    // Alternatively generate JSON output
    await app.generateJson(project, outputDir + '/documentation.json');
  }
};

createDocs();

```
These deps:

```json
{
    "typedoc": "^0.24.8",
    "typedoc-plugin-markdown": "^3.15.3",
    "typedoc-plugin-rename-defaults": "^0.6.5",
    "typescript": "^5.1.3"
}
```

tsconfig.json:

```json
{
  "compilerOptions": {
    "module": "ES2020",
    "target": "es2022",
    "lib": ["ES2021", "dom", "dom.iterable"],
    "sourceMap": true,
    "declaration": true,
    // "declarationDir": "./dts",
    "moduleResolution": "node",
    "rootDirs": ["packages/middlewares", "packages/utils", "packages/routes"],
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "typeRoots": ["packages/utils/types/dist", "./node_modules/@types"],
    "resolveJsonModule": true,
    "skipLibCheck": true
  },
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node",
    "transpileOnly": true,
    "require": ["dotenv/config", "tsconfig-paths/register"]
  },
  "exclude": ["node_modules", "dist", "*.json"]
}

```

## Environment

-   Typedoc version: 0.24.8
-   TypeScript version: 5.1.3
-   Node.js version: v18.16.0
-   OS: Ubuntu 22.04 3 LTS

**Comment by Gerrit0** [comment]
app.bootstrapWithPlugins is async, if you don't await that, no surprise that things break.

**Comment by phun-ky** [comment]
Yeah, that was quick misread on my behalf. Sorry for the noise. But I had to dig this function up myself in the source code. This should be documented IMHO
