### ISSUE TITLE
Support typescript 5.2.x

### ISSUE THREAD

**Issue by Th3S4mur41** [TypeStrong/typedoc#2373]
https://www.npmjs.com/package/typescript/v/5.2.2

Probably need to double check https://github.com/TypeStrong/typedoc/issues/2369

**Comment by TechQuery** [comment]
Yes, crashed:

```text
TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'name')
    at D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\types.js:564:100
    at Array.map (<anonymous>)
    at Object.convertType (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\types.js:564:34)
    at convertType (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\types.js:106:34)
    at Converter.convertType (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\converter.js:91:40)
    at Object.convertProperty (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\symbols.js:395:41)
    at convertSymbol (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\symbols.js:135:41)
    at convertSymbols (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\symbols.js:141:9)
    at Object.convertClassOrInterface (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\symbols.js:331:5)
    at convertSymbol (D:\Work\idea2app\Idea-React\node_modules\.pnpm\typedoc@0.24.8_typescript@5.2.2\node_modules\typedoc\dist\lib\converter\symbols.js:135:41)
 ELIFECYCLE  Command failed with exit code 6.
```
