### ISSUE TITLE
Error running typedoc

### ISSUE THREAD

**Issue by mdaguete** [TypeStrong/typedoc#239]
Hello,

When I try to exec typedoc the following error occurs

```
typedoc
/usr/local/lib/node_modules/typedoc/lib/utils/options/options.js:118
        return _.unique(result);
                 ^

TypeError: _.unique is not a function
    at Options.getDeclarationsByScope (/usr/local/lib/node_modules/typedoc/lib/utils/options/options.js:118:18)
    at getParameterHelp (/usr/local/lib/node_modules/typedoc/lib/utils/options/help.js:5:30)
    at Object.getOptionsHelp (/usr/local/lib/node_modules/typedoc/lib/utils/options/help.js:34:19)
    at CliApplication.bootstrap (/usr/local/lib/node_modules/typedoc/lib/cli.js:44:41)
    at CliApplication.Application (/usr/local/lib/node_modules/typedoc/lib/application.js:33:14)
    at new CliApplication (/usr/local/lib/node_modules/typedoc/lib/cli.js:29:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/typedoc/bin/typedoc:4:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

Node version:

```
node --version
v5.11.0
```

**Comment by 0815fox** [comment]
Can you add the output of `npm ls` please?

**Comment by mdaguete** [comment]
@0815fox 

```
➜  tmp npm ls
/Users/mdaguete/Development/tmp
└── (empty)
```

**Comment by 0815fox** [comment]
You should install typedoc in your projects directory as well:
```
$ npm install typedoc --save-dev
```
see [Readme.md](https://github.com/TypeStrong/typedoc)

**Comment by dancasey** [comment]
Same problem here as @mdaguete. I believe the issue is aab7af9e30e2e1f935cafd3f1e72e84ab77e28a8 bumped lodash from 3.x to 4.x, and 3.x had an alias for [`_.unique -> uniq`](https://github.com/lodash/lodash/blob/3.10.1/doc/README.md#_uniqarray-issorted-iteratee-thisarg) while 4.x [does not](https://lodash.com/docs#uniq).

If I'm right, then just change [this line](https://github.com/TypeStrong/typedoc/blob/53bb762ad208f2be266ece767f6204159ce71a0d/src/lib/utils/options/options.ts#L141) from `return _.unique(result);` to `return _.uniq(result);`

**Comment by blakeembrey** [comment]
Please feel free to submit a PR.

**Comment by mdaguete** [comment]
@0815fox  with the change proposed by @dancasey  it works.

Thanks!!
