### ISSUE TITLE
Error during generating Search Index

### ISSUE THREAD

**Issue by matteobruni** [TypeStrong/typedoc#2417]
## Search terms

error, search index

## Expected Behavior

I expect to not have the `undefined` error when generating the Search Index. This configuration worked in 0.24.x, it started giving error after the 0.25.x update.

## Actual Behavior

Generating the documentation folder, because of an `undefined`.

The error is:

```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at _classThis.buildSearchIndex (/xxx/tsparticles/website/node_modules/.pnpm/typedoc@0.25.2_typescript@5.2.2/node_modules/typedoc/dist/lib/output/plugins/JavascriptIndexPlugin.js:132:49)
    at /xxx/tsparticles/website/node_modules/.pnpm/typedoc@0.25.2_typescript@5.2.2/node_modules/typedoc/dist/lib/output/plugins/JavascriptIndexPlugin.js:126:64
    at /xxx/tsparticles/website/node_modules/.pnpm/typedoc@0.25.2_typescript@5.2.2/node_modules/typedoc/dist/lib/output/renderer.js:268:68
    at Array.map (<anonymous>)
    at _classThis.runPreRenderJobs (/xxx/tsparticles/website/node_modules/.pnpm/typedoc@0.25.2_typescript@5.2.2/node_modules/typedoc/dist/lib/output/renderer.js:268:55)
    at _classThis.render (/xxx/tsparticles/website/node_modules/.pnpm/typedoc@0.25.2_typescript@5.2.2/node_modules/typedoc/dist/lib/output/renderer.js:251:24)
    at async _classThis.generateDocs (/xxx/tsparticles/website/node_modules/.pnpm/typedoc@0.25.2_typescript@5.2.2/node_modules/typedoc/dist/lib/application.js:407:13)
    at async file:///xxx/tsparticles/website/docs-gen.js:62:13
```

## Steps to reproduce the bug

- Clone https://github.com/tsparticles/website
- Run `pnpm install`
- Run `pnpm run build:docs` (it takes a while)

## Environment

-   Typedoc version: 0.25.2 (tried also 0.25.1)
-   TypeScript version: 5.2.2
-   Node.js version: 18
-   OS: macOS

**Comment by Gerrit0** [comment]
If possible, please reduce this to a _minimal_ reproduction. I don't have time to investigate everyone's special build system 

Also, I strongly recommend tossing `//@ts-check` at the top of your random JS scripts. If you'd done this, you would have noticed a type error in your docs-gen script which I suspect is the reason for this.

**Comment by matteobruni** [comment]
> If possible, please reduce this to a _minimal_ reproduction. I don't have time to investigate everyone's special build system
> 
> Also, I strongly recommend tossing `//@ts-check` at the top of your random JS scripts. If you'd done this, you would have noticed a type error in your docs-gen script which I suspect is the reason for this.

The type error fix did the job. Thanks, I didn't notice that!
