### ISSUE TITLE
Interface and Class with same name leeds to endless loop

### ISSUE THREAD

**Issue by besessener** [TypeStrong/typedoc#2495]
## Search terms

- RangeError: Maximum call stack size exceeded
- interface and claas that implements it ith same name

## Expected Behavior

no crash

## Actual Behavior

```
TypeDoc exiting with unexpected error:
RangeError: Maximum call stack size exceeded
    at ProjectReflection.getReflectionById (C:\Repos\Claas\cde-fe-app\node_modules\typedoc\dist\lib\models\reflections\project.js:193:22)
    at get reflection [as reflection] (C:\Repos\Claas\cde-fe-app\node_modules\typedoc\dist\lib\models\types.js:678:35)
    at C:\Repos\Claas\cde-fe-app\node_modules\typedoc\dist\lib\output\themes\default\templates\hierarchy.js:17:30
    at Array.map (<anonymous>)
    at fullHierarchy (C:\Repos\Claas\cde-fe-app\node_modules\typedoc\dist\lib\output\themes\default\templates\hierarchy.js:16:33)
    at C:\Repos\Claas\cde-fe-app\node_modules\typedoc\dist\lib\output\themes\default\templates\hierarchy.js:17:44
    at Array.map (<anonymous>)
    at fullHierarchy (C:\Repos\Claas\cde-fe-app\node_modules\typedoc\dist\lib\output\themes\default\templates\hierarchy.js:16:33)
    at C:\Repos\Claas\cde-fe-app\node_modules\typedoc\dist\lib\output\themes\default\templates\hierarchy.js:17:44
    at Array.map (<anonymous>)
```

## Steps to reproduce the bug

```
export interface Foo {
  type?: string;
  name?: string;
  id: string;
  hidden?: boolean;
}

export class Foo extends Serializable implements Foo {
  constructor(params: Foo) {
    super(params);
  }
}
```

The above example might look strange. Like this, the class `Foo` does not need to implement all the properties of interface `Foo`. The properties are just there (Mixin).

My assumption is, that this code leads to an endless loop.....or actually endless recursion of function `function fullHierarchy(context, root)`

## Environment

-   Typedoc version: 0.25.7
-   TypeScript version: 5.1.6
-   Node.js version: 21.6.1
-   OS: Windows 11

**Comment by csvtuda** [comment]
Can confirm, I am seeing the same behaviour. MRE:

```ts
// index.ts
interface IAnimal {
  name: number;
}

interface IFish extends IAnimal {
  maxDepth: number;
}

class IFish implements IFish {}

const f = new IFish();
console.log(f.name, f.maxDepth);
```

Result:
```console
$ npx typedoc index.ts
TypeDoc exiting with unexpected error:
RangeError: Maximum call stack size exceeded
    at fullHierarchy (/home/me/fishProject/node_modules/typedoc/dist/lib/output/themes/default/templates/hierarchy.js:11:21)
    at /home/me/fishProject/node_modules/typedoc/dist/lib/output/themes/default/templates/hierarchy.js:17:44
    at Array.map (<anonymous>)
    at fullHierarchy (/home/me/fishProject/node_modules/typedoc/dist/lib/output/themes/default/templates/hierarchy.js:16:33)
    at /home/me/fishProject/node_modules/typedoc/dist/lib/output/themes/default/templates/hierarchy.js:17:44
    at Array.map (<anonymous>)
    at fullHierarchy (/home/me/fishProject/node_modules/typedoc/dist/lib/output/themes/default/templates/hierarchy.js:16:33)
    at /home/me/fishProject/node_modules/typedoc/dist/lib/output/themes/default/templates/hierarchy.js:17:44
    at Array.map (<anonymous>)
    at fullHierarchy (/home/me/fishProject/node_modules/typedoc/dist/lib/output/themes/default/templates/hierarchy.js:16:33)

```

**Comment by Gerrit0** [comment]
Huh, I guess that's valid TS... didn't think I had to worry about infinite loops when dealing with inheritance.
