### ISSUE TITLE
Exception when writing HTML output:`TypeError: project.getReflectionsByKind is not a function`

### ISSUE THREAD

**Issue by marwie** [TypeStrong/typedoc#2536]
## Expected Behavior

Produce HTML or json output from a typescript package running from mjs script

## Actual Behavior

Exception when trying to produce the output
```js
[debug] Finished conversion in 2799ms
TypeError: project.getReflectionsByKind is not a function
    at getHierarchyRoots (/Users/user/git/my-package/node_modules/typedoc/dist/lib/output/themes/lib.js:126:32)
    at DefaultTheme.getUrls (/Users/user/git/my-package/node_modules/typedoc/dist/lib/output/themes/default/DefaultTheme.js:122:41)
    at _classThis.render (/Users/user/git/my-package/node_modules/typedoc/dist/lib/output/renderer.js:256:38)
    at async _classThis.generateDocs (/Users/user/git/my-package/node_modules/typedoc/dist/lib/application.js:407:13)
    at async main (file:///Users/user/git/my-package/tools/build_api_docs.mjs:53:9)
```

## Steps to reproduce the bug

This is the code running
```mjs
const app = await TypeDoc.Application.bootstrapWithPlugins({
        entryPoints: [dir + "/src/entry.ts"],
        // entryPointStrategy: "Packages",
        readme: "none",
        disableSources: true,
        excludeExternals: true,
        // skipErrorChecking: true,
        includeVersion: true,
        excludeInternal: true,
        excludeProtected: true,
        excludePrivate: true,
        // exclude: "**/dist/**|**/_Ignore*.ts",
        // externalPattern: "**/node_modules/**",
        githubPages: false,
    });
    // If you want TypeDoc to load tsconfig.json / typedoc.json files
    app.options.addReader(new TypeDoc.TSConfigReader());
    const project = app.convert();
    if (project) {
        // Project may not have converted correctly
        const version = "1.0.0";
        const outputDir = "documentation/api/my-package/" + version;
        await app.generateDocs(project, outputDir);
        // await app.generateJson(project, outputDir + "/documentation.json");
    }
```

```json
{
  "compilerOptions": {   
    "target": "ESNext", 
    "module": "ESNext",
    "outDir": "dist",
    "useDefineForClassFields": true,
    "lib": ["ESNext", "DOM"],
    "moduleResolution": "Node",
    "strict": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "noEmit": true,
    "noUnusedLocals": false,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitAny": false,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "allowJs": true,
    "types": [
      "three",
      "vite/client"
    ]
  },
  "include": [
    "src/*.ts"
  ],
  "exclude": ["node_modules", "dist", "lib", "vite.config.ts", "tests"]
}
```

## Environment

-   Typedoc version: 0.25.12
-   TypeScript version: 5.1.6
-   Node.js version: 20.10.0
-   OS: OSX Sonoma 14.1.1

**Comment by marwie** [comment]
Caused by not awaiting project.convert()
`const project = await app.convert();` fixed it
