### ISSUE TITLE
Unable to build the site

### ISSUE THREAD

**Issue by xuhdev** [TypeStrong/typedoc#2538]
## Search terms

doc, site

## Expected Behavior

Following the README of https://github.com/TypeStrong/typedoc-site leads to a site built.

## Actual Behavior

```shell
$ npm run serve

> typedoc-site@1.0.0 serve
> npx @11ty/eleventy --serve

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering liquid template ./guides/plugins.md (via TemplateContentRenderError)
[11ty] 2. ENOENT: no such file or directory, open '/home/user/src/typedoc-site/_includes/plugin_content.txt', file:./guides/plugins.md, line:9, col:1 (via RenderError)
[11ty] 3. ENOENT: no such file or directory, open '/home/user/src/typedoc-site/_includes/plugin_content.txt' (via Error)
[11ty] 
[11ty] Original error stack trace: Error: ENOENT: no such file or directory, open '/home/user/src/typedoc-site/_includes/plugin_content.txt'
[11ty]     at Object.openSync (node:fs:582:18)
[11ty]     at Object.readFileSync (node:fs:461:35)
[11ty]     at Object.<anonymous> (/home/user/src/typedoc-site/.eleventy.js:31:12)
[11ty]     at Object.<anonymous> (/home/user/src/typedoc-site/node_modules/@11ty/eleventy/src/BenchmarkGroup.js:32:26)
[11ty]     at Tag.render (/home/user/src/typedoc-site/node_modules/@11ty/eleventy/src/Engines/Liquid.js:170:39)
[11ty]     at render.next (<anonymous>)
[11ty]     at toPromise (/home/user/src/typedoc-site/node_modules/liquidjs/dist/liquid.node.cjs.js:451:32)
[11ty]     at toPromise (/home/user/src/typedoc-site/node_modules/liquidjs/dist/liquid.node.cjs.js:457:25)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async toPromise (/home/user/src/typedoc-site/node_modules/liquidjs/dist/liquid.node.cjs.js:459:25)
[11ty] Copied 7 files / Wrote 0 files in 0.34 seconds (v2.0.1)
```

## Steps to reproduce the bug

1. Clone https://github.com/TypeStrong/typedoc-site.
2. `npm i`
3. `npm run serve`

**Comment by Gerrit0** [comment]
Updated - https://github.com/TypeStrong/typedoc-site/commit/fedde993764873a046cb81c5cc65180ee9f59c8b

`npm run prebuild` is necessary, I don't have that set up as a `preserve` as well since it takes a bit to run... maybe I should..

**Comment by xuhdev** [comment]
`npm run prebuild` leads to the following error for me:

```
> ts-node --esm scripts/plugins.ts

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/user/src/typedoc-site/scripts/plugins.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:866:22)
    at async nextLoad (node:internal/modules/esm/hooks:866:22)
    at async Hooks.load (node:internal/modules/esm/hooks:449:20)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
```

**Comment by Gerrit0** [comment]
You're running with Node 20 or something, I haven't gotten around to fighting through the breaking changes they introduced then... PR welcome, or just use node 18 for that repo for now.
