### ISSUE TITLE
Please be compatible with node 14.21.0

### ISSUE THREAD

**Issue by rongqb1990** [TypeStrong/typedoc#2677]
## Search terms

```text
node_modules/.pnpm/typedoc@0.26.6_typescript@5.5.4/node_modules/typedoc/dist/lib/models/reflections/abstract.js:326
2024-08-20 14:43:57.735                 this._alias ||= this.getUniqueAliasInPage(this.name.replace(/\W/g, "_") || `reflection-${this.id}`);
2024-08-20 14:43:57.735                             ^^^
2024-08-20 14:43:57.735 
2024-08-20 14:43:57.735 SyntaxError: Unexpected token '||='
2024-08-20 14:43:57.735     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
2024-08-20 14:43:57.735     at Module._compile (internal/modules/cjs/loader.js:1049:27)
2024-08-20 14:43:57.735     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2024-08-20 14:43:57.735     at Module.load (internal/modules/cjs/loader.js:950:32)
2024-08-20 14:43:57.735     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2024-08-20 14:43:57.735     at Module.require (internal/modules/cjs/loader.js:974:19)
2024-08-20 14:43:57.735     at require (internal/modules/cjs/helpers.js:101:18)
2024-08-20 14:43:57.735     at Object. 
```

## Environment

-   Typedoc version: 0.26.0
-   TypeScript version: 5.5.4
-   Node.js version: 14.21.0
-   OS: macOS

**Comment by Gerrit0** [comment]
Supporting node releases which have passed end of life isn't worth the limited time I have for typedoc. This is definitely a wontfix.
