### ISSUE TITLE
crashes when upgrading from 0.26.11 to 0.27.0 or 0.27.1

### ISSUE THREAD

**Issue by pamapa** [TypeStrong/typedoc#2789]
## Expected Behavior

Should not crash.

## Actual Behavior

Crashes.

## Steps to reproduce the bug

You can see the behavior in this pull request: https://github.com/authts/oidc-client-ts/pull/1757
Error:
```sh
Run npm run typedoc
  npm run typedoc
  shell: /usr/bin/bash -e {0}

> oidc-client-ts@3.1.0 typedoc
> typedoc

TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'TypeParameter')
    at ReferenceType.createSymbolReference (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/models/types.js:782:70)
    at Object.convert (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/types.js:190:35)
    at convertType (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/types.js:80:38)
    at Converter.convertType (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/converter.js:330:20)
    at file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/symbols.js:333:117
    at Array.map (<anonymous>)
    at Object.convertClassOrInterface (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/symbols.js:333:88)
    at convertSymbol (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/symbols.js:122:41)
    at Object.convertAlias (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/symbols.js:494:9)
    at convertSymbol (file:///home/runner/work/oidc-client-ts/oidc-client-ts/node_modules/typedoc/dist/lib/converter/symbols.js:122:41)
Error: Process completed with exit code 6.
```

## Environment

-   Typedoc version: 0.27.1
-   TypeScript version: 5.4.2
-   Node.js version: 18.x
-   OS: Linux

**Comment by willeastcott** [comment]
This is happening for the [PlayCanvas API reference](https://github.com/playcanvas/api-reference) too after the same upgrade.

**Comment by Gerrit0** [comment]
This appears to be because of the older TS version - I really need to get some automation in place to properly test with older TS versions...

**Comment by Gerrit0** [comment]
Annoyingly small patch with patch-package to make it work... will make a release with this later today.

```ts
diff --git a/node_modules/typedoc/dist/lib/models/types.js b/node_modules/typedoc/dist/lib/models/types.js
index 15ce050..136db9e 100644
--- a/node_modules/typedoc/dist/lib/models/types.js
+++ b/node_modules/typedoc/dist/lib/models/types.js
@@ -1,4 +1,4 @@
-import * as ts from "typescript";
+import ts from "typescript";
 import { getQualifiedName } from "../utils/tsutils.js";
 import { ReflectionSymbolId } from "./reflections/ReflectionSymbolId.js";
 import { findPackageForPath } from "../utils/fs.js";
```
