### ISSUE TITLE
extends class from existed ES6 javascript file Error 

### ISSUE THREAD

**Issue by jianhaozh** [TypeStrong/typedoc#289]
when i have exist js class file ,code as below:

```javascript
'use strict';
class BaseClass{
    constructor() {}
    sum(a,b){
        return a + b;
    }
}

exports = BaseClass;
```

and a ts file ,defined a class , at the same folder,code as below:

```typescript
'use strict';
import BaseClass = require('BaseClass');
export class User extends BaseClass{

    constructor (){
        super();
    }

    /**
     * @param a string  this is a string
     * @param a string  this is b string
     * @returns      Comment for special return value.
     */
    public sumStr(a:string,b:string):string{
        return a + b;
    }

}
```

when i try to execute the command : `typedoc --ignoreCompilerErrors --target ES6 --out doc modules` 
folder modules which contains the BaseClass  class and the User class code,i got the error below:

```
C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\types\reference.js:26
        return !!(type.flags & 80896);
                      ^

TypeError: Cannot read property 'flags' of undefined
    at ReferenceConverter.supportsNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\types\reference.js:26:23)
    at Converter.convertType (C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\converter.js:127:31)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\nodes\class.js:47:63
    at Context.withScope (C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\context.js:99:9)
    at ClassConverter.convert (C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\nodes\class.js:35:17)
    at Converter.convertNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\converter.js:117:53)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\nodes\block.js:71:33
    at Array.forEach (native)
    at BlockConverter.convertStatements (C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\nodes\block.js:69:29)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\typedoc\lib\converter\nodes\block.js:55:27

```

so far , i modify the code below to avoid the error and get the doc generate as normal:

![qq 20160912172107](https://cloud.githubusercontent.com/assets/2909736/18431074/eedb7e70-790d-11e6-9da1-ed3d52ed3841.png)

at file /lib/converter/converter.js

_Note: Edited to style code blocks_

**Comment by Gerrit0** [comment]
This appears to work properly in the latest version,
