### ISSUE TITLE
Cannot read Flags of undefined

### ISSUE THREAD

**Issue by dharsanav** [TypeStrong/typedoc#374]
Iam getting 

> **cannot read flags of undefined error**

when trying to run typedoc on entire project . But it works perfectly fine when i generate documentation for a single file .

Any idea why this happens and how to run typedoc on my entire project?

**Comment by aciccarello** [comment]
Hi @shaitya, do you have any further information? I doubt anyone will be able to diagnose your problem with that amount of information.

**Comment by shaitya** [comment]
I have an angular 2 project say Test . I run typedoc via cli

>  typedoc --target ES5 --module commonjs --ignoreCompilerErrors    --out docs src

src folder contains my source code .

When i run the above command on src folder Iam getting 

`Using TypeScript 2.0.6 from path\npm\node_modules\typedoc\node_modules\typescript\lib
path\npm\node_modules\typedoc\lib\converter\types\reference.js:26
        return !!(type.flags & ts.TypeFlags.ObjectType);
                      ^

TypeError: Cannot read property 'flags' of undefined
    at ReferenceConverter.supportsNode (path\npm\node_modules\typedoc\lib\converter\types\reference.js:26:23)
    at Converter.convertType (path\npm\node_modules\typedoc\lib\converter\converter.js:129:31)
    at path\npm\node_modules\typedoc\lib\converter\nodes\class.js:52:63
    at Context.withScope (path\npm\node_modules\typedoc\lib\converter\context.js:98:9)
    at ClassConverter.convert (path\npm\node_modules\typedoc\lib\converter\nodes\class.js:36:17)
    at Converter.convertNode (path\npm\node_modules\typedoc\lib\converter\converter.js:119:53)
    at path\npm\node_modules\typedoc\lib\converter\nodes\block.js:71:33
    at Array.forEach (native)
    at BlockConverter.convertStatements (path\npm\node_modules\typedoc\lib\converter\nodes\block.js:69:29)
    at path\npm\node_modules\typedoc\lib\converter\nodes\block.js:55:27
`
I have TypeDoc 0.5.1 installed globally.

Now if run the typedoc command over a single file as

> typedoc --target ES5 --module commonjs --ignoreCompilerErrors    --out docs src/app/app.component.ts   

Documentation is generated,

**Comment by aciccarello** [comment]
This may be the same issue as #289
