### ISSUE TITLE
Crash in `converter/plugins/SourcePlugin.js:112`

### ISSUE THREAD

**Issue by MarcusRiemer** [TypeStrong/typedoc#420]
Attempting to compile [my project](https://bitbucket.org/marcusriemer/esqulino) results in a plain crash of typedoc `0.5.6`:

    marcus@mri-tp:~/p/s/client >>> ./node_modules/typedoc/bin/typedoc --out doc .                                                                                                                                git:widget-hierarchy-refactor *
    
    Using TypeScript 2.1.6 from /home/marcus/projects/scratch-sql/client/node_modules/typedoc/node_modules/typescript/lib
    /home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:112
                        if (!Object.prototype.hasOwnProperty.call(directory, path)) {
                                                             ^
    
    TypeError: Cannot convert undefined or null to object
        at hasOwnProperty (<anonymous>)
        at /home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:112:58
        at Array.forEach (native)
        at /home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:111:33
        at Array.forEach (native)
        at SourcePlugin.onEndResolve (/home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:103:23)
        at triggerEvents (/home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/utils/events.js:121:43)
        at triggerApi (/home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/utils/events.js:106:13)
        at eventsApi (/home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/utils/events.js:20:18)
        at Converter.EventDispatcher.trigger (/home/marcus/projects/scratch-sql/client/node_modules/typedoc/dist/lib/utils/events.js:261:13)

Specifying the `--mode modules` property did not help either.

**Comment by Timmaex** [comment]
Bump, same here.

**Comment by sennl** [comment]
Same here.
Typescript 2.1.6
Typedoc 0.5.7

**Comment by nuthalapativarun** [comment]
What's the solution for the above error?

**Comment by nuthalapativarun** [comment]
@aciccarello Do you know a solution for the problem?

**Comment by aciccarello** [comment]
No one has worked on a solution yet hence why it is still open. PRs or any other help are always welcome :smile:

**Comment by Gerrit0** [comment]
As far as I can tell this has been fixed, that line is hit ~20 times while testing with no crash, please open a new issue if you are still experiencing this in the latest version.
