### ISSUE TITLE
TypeError: Cannot convert undefined or null to object at hasOwnProperty (<anonymous>)

### ISSUE THREAD

**Issue by nuthalapativarun** [TypeStrong/typedoc#458]
Getting the above error when using typedoc for Angular2 Cli project and trying to generate documentation for my project.

`$ typedoc --out outpath/ angular2cli/ `

but i'm getting the following errors

```
Using TypeScript 2.2.1 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/lib
/usr/local/lib/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:122
                    if (!Object.prototype.hasOwnProperty.call(directory, path)) {
                                                         ^

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at /usr/local/lib/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:122:58
    at Array.forEach (native)
    at /usr/local/lib/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:121:33
    at Array.forEach (native)
    at SourcePlugin.onEndResolve (/usr/local/lib/node_modules/typedoc/dist/lib/converter/plugins/SourcePlugin.js:113:23)
    at triggerEvents (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:129:43)
    at triggerApi (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:111:13)
    at eventsApi (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:21:18)
    at Converter.EventDispatcher.trigger (/usr/local/lib/node_modules/typedoc/dist/lib/utils/events.js:280:13)

```

Is there any way to fix this error?

**Comment by aciccarello** [comment]
Duplicates #420
