### ISSUE TITLE
Crash in `converter/plugins/SourcePlugin.js:128:22

### ISSUE THREAD

**Issue by zelein** [TypeStrong/typedoc#462]
I'm attempting to run typedoc `0.5.9`  on a project that is all modules but has a single non-module script file. 

Run with these params:

`typedoc --out ./docs/ --mode modules --excludeExternals --module commonjs --target ES6 --readme ./README.md/ ./src/`

I get this stacktrace:
```
Using TypeScript 2.2.1 from E:\git\apis\git_rest\node_modules\typedoc\node_modules\typescript\lib
E:\git\apis\git_rest\node_modules\typedoc\dist\lib\converter\plugins\SourcePlugin.js:128
            directory.files.push(file);
                     ^

TypeError: Cannot read property 'files' of undefined
    at E:\git\apis\git_rest\node_modules\typedoc\dist\lib\converter\plugins\SourcePlugin.js:128:22
    at Array.forEach (native)
    at SourcePlugin.onEndResolve (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\converter\plugins\SourcePlugin.js:113:23)
    at triggerEvents (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\utils\events.js:129:43)
    at triggerApi (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\utils\events.js:111:13)
    at eventsApi (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\utils\events.js:21:18)
    at Converter.EventDispatcher.trigger (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\utils\events.js:280:13)
    at Converter.resolve (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\converter\converter.js:183:14)
    at Converter.convert (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\converter\converter.js:110:28)
    at CliApplication.Application.convert (E:\git\apis\git_rest\node_modules\typedoc\dist\lib\application.js:78:37)

```

I did a little digging and and the path variable that is set just before the crash is `test/files` which is a folder that contains the non-module script file. 

I realize typedoc does not support building documentation for files and modules, and I am not expecting it to. I was just not expecting it to crash in the case it came across a non-module.

This may be related to: #420

**Comment by aciccarello** [comment]
Thanks for the detailed report. I think it is more likely related to #440. I'll close this a a duplicate.
