### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by buschtoens** [TypeStrong/typedoc#513]
```
$ yarn run generate-docs
yarn run v0.24.5
$ typedoc --out dist/docs

Using TypeScript 2.3.2 from /home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/node_modules/typescript/lib
/home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/nodes/export.js:42
            symbol.declarations.forEach(function (declaration) {
                               ^

TypeError: Cannot read property 'forEach' of undefined
    at ExportConverter.convert (/home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/nodes/export.js:42:32)
    at Converter.convertNode (/home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/converter.js:126:53)
    at /home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/nodes/block.js:85:29
    at Array.forEach (native)
    at BlockConverter.convertStatements (/home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/nodes/block.js:84:26)
    at /home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/nodes/block.js:62:27
    at Context.withScope (/home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/context.js:107:9)
    at /home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/nodes/block.js:61:25
    at Context.withSourceFile (/home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/context.js:87:9)
    at BlockConverter.convertSourceFile (/home/jan/github/ember-cli-typedoc-error-demo/node_modules/typedoc/dist/lib/converter/nodes/block.js:58:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Demo repository here: https://github.com/buschtoens/ember-cli-typedoc-error-demo

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES6",
    "allowJs": true,
    "moduleResolution": "node",
    "noEmitOnError": false,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "ember-cli-typedoc-error-demo/tests/*": ["tests/*"],
      "ember-cli-typedoc-error-demo/*": ["app/*"]
    }
  },
  "include": [
    "app/**/*",
    "tests/**/*"
  ]
}
```

**Comment by josiahruddell** [comment]
I'm having the same problem.

`> ./node_modules/.bin/typedoc --json --out dist/docs src/model/assertion`

```
Using TypeScript 2.3.2 from /work/story-runner/node_modules/typedoc/node_modules/typescript/lib
/work/story-runner/node_modules/typedoc/dist/lib/converter/nodes/export.js:42
            symbol.declarations.forEach(function (declaration) {
                               ^

TypeError: Cannot read property 'forEach' of undefined
    at ExportConverter.convert (/work/story-runner/node_modules/typedoc/dist/lib/converter/nodes/export.js:42:32)```

```
> node -v
v6.10.1
```

**Comment by kevineaton** [comment]
Has there been any movement on this? I am having this issue with a very simple Express project while testing out documentation generators.

`node -v`
`v8.1.4`

`typedoc -v`
```
TypeDoc 0.7.1
Using TypeScript 2.3.2 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/lib
```

```
typedoc --mode modules --out ./docs ./src

Using TypeScript 2.3.2 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/lib
/usr/local/lib/node_modules/typedoc/dist/lib/converter/nodes/export.js:42
            symbol.declarations.forEach(function (declaration) {
                               ^

TypeError: Cannot read property 'forEach' of undefined
    at ExportConverter.convert (/usr/local/lib/node_modules/typedoc/dist/lib/converter/nodes/export.js:42:32)
    at Converter.convertNode (/usr/local/lib/node_modules/typedoc/dist/lib/converter/converter.js:126:53)
    at /usr/local/lib/node_modules/typedoc/dist/lib/converter/nodes/block.js:85:29
    at Array.forEach (native)
    at BlockConverter.convertStatements (/usr/local/lib/node_modules/typedoc/dist/lib/converter/nodes/block.js:84:26)
    at /usr/local/lib/node_modules/typedoc/dist/lib/converter/nodes/block.js:62:27
    at Context.withScope (/usr/local/lib/node_modules/typedoc/dist/lib/converter/context.js:107:9)
    at /usr/local/lib/node_modules/typedoc/dist/lib/converter/nodes/block.js:61:25
    at Context.withSourceFile (/usr/local/lib/node_modules/typedoc/dist/lib/converter/context.js:87:9)
    at BlockConverter.convertSourceFile (/usr/local/lib/node_modules/typedoc/dist/lib/converter/nodes/block.js:58:17)

I feel like I am missing something, but the error here is not helpful.
```

**Comment by aciccarello** [comment]
It has something to do with default exports. In @buschtoens 's demo repo (thanks for that) it occurs in [resolver.js](https://github.com/buschtoens/ember-cli-typedoc-error-demo/blob/master/app/resolver.js) which looks like the following.

```TypeScript
import Resolver from 'ember-resolver';

export default Resolver;
```

**Comment by kevineaton** [comment]
I opened a PR with a simple change that seemed to fix it for me. Essentially, I just do an if() on the decorators to make sure they are not undefined. There is probably something more to do to jump in and find out why they are undefined, but this at least unblocked by particular use case. It's a super small fix for the symptom.

**Comment by natevoci** [comment]
Just FYI, Kevin's PR does essentially the same thing as mine in src/lib/converter/nodes/export.ts, but I didn't change src/test/renderer/specs/classes/_default_export_.defaultexportedclass.html in mine

@aciccarello, you're correct about it being related to default exports. I noted the same thing in the comments of my PR. Wow. That was 7 weeks ago now. Should I have put the comments in here as well?

I haven't spent much time with typedoc yet. In this situation, is the fix Kevin and I implemented going to break anything? I just did a test creating two files

`Types.ts`
```
export enum Types {
	Multiple = 0,
	Single = 1,
}
```

and `index.ts` that imports it and exports it as default.
```
import { Types } from './Types';
export default Types;
```

In the json output both modules are there, and the Types module includes the Types Enumeration child, so it appears to be working to me.

**Comment by aciccarello** [comment]
@natevoci Oh, I didn't even notice that PR. I don't know the code base very well and the unit test coverage is a little limited so I'm slow to merge changes. If you could add the test case to your PR, that would be great.

When I get some time I'll look at #518 vs #562.

**Comment by kevineaton** [comment]
My PR is very simple and I didn't notice #518 when I made mine, so they are likely redundant. I can look into writing a test when I get some time, but I am not entirely sure how exactly this issue is coming up. It looks like in some cases the symbols simply aren't being populated, and I am not familiar enough with the process to confidently ensure I know what to test for.

Again, for what it's worth, with my PR (and I presume with #518 ) my documentation is complete and it runs.

**Comment by fuckbetterdiscord** [comment]
didn't work because this is garbage, cant uninstall because this is garbage
