### ISSUE TITLE
TypeError on basic run

### ISSUE THREAD

**Issue by crisboarna** [TypeStrong/typedoc#757]
Hi, 

I am trying to run TypeDoc on a small project I created but am running into issues getting the most basic example running.

I have installed it locally via `npm i -D typedoc` and by executing 
- `./node_modules/.bin/typedoc --out dist/docs .`
- `./node_modules/.bin/typedoc ./src --out ./docs --module commonjs --target ES5 --mode file`
- ` ./node_modules/.bin/typedoc --out dist/docs --mode modules .`

They all result in the following error stack:
```
/Project/node_modules/typedoc/dist/lib/output/plugins/MarkedPlugin.js:43
        Marked.setOptions({
               ^

TypeError: Marked.setOptions is not a function
    at MarkedPlugin.initialize (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/output/plugins/MarkedPlugin.js:43:16)
    at MarkedPlugin.AbstractComponent [as constructor] (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/utils/component.js:87:15)
    at MarkedPlugin.RendererComponent [as constructor] (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/output/components.js:21:42)
    at MarkedPlugin.ContextAwareRendererComponent [as constructor] (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/output/components.js:29:47)
    at new MarkedPlugin (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/output/plugins/MarkedPlugin.js:31:47)
    at Renderer.ChildableComponent.addComponent /Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/utils/component.js:159:68)
    at Renderer.ChildableComponent [as constructor] (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/utils/component.js:133:19)
    at new Renderer (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/output/renderer.js:31:42)
    at CliApplication.ChildableComponent.addComponent (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/utils/component.js:159:68)
    at CliApplication.Application [as constructor] (/Projects/aws-lex-proxy/node_modules/typedoc/dist/lib/application.js:38:32)
```
This is on typedoc 0.11.1.
Am I missing something or why is it exhibiting this behavior ?

**Comment by crisboarna** [comment]
I fixed this error by `npm i -D marked` but now I am running into another issue. 
- It throws error on `node_modules` folder although i specify run as `./node_modules/.bin/typedoc ./src --out ./docs --module commonjs --target ES5 --mode file` which should make it ignore `node_modules`.
- If I add `--exclude ./node_modules/*` it starts throwing errors for 
```
Error: /Projects/aws-lex-proxy/node_modules/typescript/lib/typescript.d.ts(3462)
 Declaration or statement expected.
Error: /Projects/aws-lex-proxy/node_modules/typescript/lib/typescript.d.ts(3530)
 ']' expected.
Error: /Projects/aws-lex-proxy/node_modules/typescript/lib/typescript.d.ts(3530)
 ')' expected.

```

Anybody have any ideas on why it is throwing these issues ?

**Comment by crisboarna** [comment]
Fixed by creating `tdconfig.json` and running with `    "generate-docs": "./node_modules/.bin/typedoc --out ./doc --module modules --hideGenerator --tsconfig tdconfig.json"`
