### ISSUE TITLE
Add support for ES6 modules

### ISSUE THREAD

**Issue by sebastian-lenz** [TypeStrong/typedoc#98]

**Comment by robertbaker** [comment]
I'm guessing this is my problem?

Using TypeScript 1.5.0-beta from C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\bin

stderr: C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:5079
                    classMember.implementationOf = new td.models.ReferenceType
                                                 ^
TypeError: Cannot set property 'implementationOf' of undefined
    at C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:5079:50
    at Array.forEach (native)
    at ImplementsPlugin.analyzeClass (C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:5064:46)
    at C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:5126:35
    at Array.forEach (native)
    at ImplementsPlugin.onResolve (C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:5120:49)
    at Converter.EventDispatcher.dispatch (C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:102:34)
    at Converter.resolve (C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:1996:26)
    at Converter.convert (C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:1951:36)
    at Application.convert (C:\Users\Robert\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc.js:418:41)

**Comment by sebastian-lenz** [comment]
Hi Robert! No, this error seems unrelated. Looks like a class does not implement all interface members. I'll add a fix for that.

**Comment by sebastian-lenz** [comment]
Version 0.3.6 is now on NPM containing the fix.

**Comment by Spittal** [comment]
Very interested in this feature.

**Comment by aciccarello** [comment]
This should be working. If there is a specific issue please search for an open issue to upvote or open a new one.
